/**
 * Client-side utilities for invoking durable workflows.
 */

import { LambdaClient, InvokeCommand } from "@aws-sdk/client-lambda";

export interface WorkflowDescriptor {
  __workflow: true;
  name: string;
  functionName: string;
}

export interface WorkflowRunResult<T = unknown> {
  executionId: string;
  result: T;
  steps: string[];
}

export interface StartOptions {
  /** AWS region override */
  region?: string;
  /** Additional Lambda invocation parameters */
  clientConfig?: Record<string, unknown>;
}

/**
 * Start a workflow execution by invoking its Lambda function.
 *
 * @param workflow - The workflow descriptor (generated by client mode transform)
 * @param input - The input payload for the workflow
 * @param opts - Optional configuration
 * @returns The workflow execution result
 */
export async function start<T = unknown>(
  workflow: WorkflowDescriptor,
  input: unknown,
  opts?: StartOptions
): Promise<WorkflowRunResult<T>> {
  if (!workflow.__workflow) {
    throw new Error("Invalid workflow descriptor. Expected a transformed workflow import.");
  }

  const client = new LambdaClient(opts?.clientConfig ?? {});

  const command = new InvokeCommand({
    FunctionName: workflow.functionName,
    Payload: new TextEncoder().encode(
      JSON.stringify({
        input,
        executionId: `exec-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
      })
    ),
  });

  const response = await client.send(command);

  if (response.FunctionError) {
    const errorPayload = response.Payload
      ? JSON.parse(new TextDecoder().decode(response.Payload))
      : { message: "Unknown error" };
    throw new Error(
      `Workflow "${workflow.name}" failed: ${errorPayload.errorMessage || errorPayload.message}`
    );
  }

  if (!response.Payload) {
    throw new Error(`Workflow "${workflow.name}" returned no payload`);
  }

  return JSON.parse(new TextDecoder().decode(response.Payload)) as WorkflowRunResult<T>;
}

/**
 * Get the status/result of a workflow run by execution ID.
 * (Placeholder — in production this would query a state store.)
 *
 * @param workflow - The workflow descriptor
 * @param executionId - The execution ID to look up
 * @returns The workflow run result
 */
export async function getRun<T = unknown>(
  _workflow: WorkflowDescriptor,
  _executionId: string
): Promise<WorkflowRunResult<T>> {
  throw new Error(
    "getRun() is not yet implemented. " +
      "In production, this would query a DynamoDB table or Step Functions execution."
  );
}
